### ISSUE TITLE
Fix master

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g7_sf#42]

**Comment by SofiaTCastillo** [comment]
Trabajo Realizado
Se llevaron a cabo diversas actualizaciones y mejoras en el proyecto para optimizar la funcionalidad y mejorar la eficiencia del código existente.

Refactorización y Mejora de Servicios:
Se realizaron mejoras significativas en los servicios de Especialidad y Paciente.
En EspecialidadServiceImplJpa y PacienteServiceImplJpa, se optimizó la lógica de negocio para mejorar la eficiencia y reducir la complejidad de los métodos, garantizando un mejor rendimiento y mantenimiento del código.

Actualización de Dependencias:
Se modificó el archivo pom.xml para ajustar las dependencias del proyecto. Estos ajustes permiten mejorar la estabilidad y asegurar la compatibilidad con los requisitos actuales de la aplicación.

Validaciones en la Entidad Paciente:
La entidad Paciente fue actualizada para incluir validaciones adicionales. 

Cambios Locales no Subidos al Repositorio:
Durante el proceso de refactorización, se realizaron cambios en el archivo de configuración application.properties con ajustes específicos al entorno de desarrollo. Sin embargo, este archivo no fue incluido en el commit para evitar exponer configuraciones sensibles o específicas de un entorno local.
Además, se modificó un directorio llamado 2024_gc_p3_g7_sf/, el cual contiene archivos y datos que no forman parte de esta versión del repositorio. Se decidió no incluir este directorio en el commit porque actualmente es parte de configuraciones locales , subirlas podria corromper el proyecto.
Adjunto imagen del proyecto levantado en el local:

![image](https://github.com/user-attachments/assets/84bf0f87-a13d-42bf-82bf-3abe8556f05a)
