### ISSUE TITLE
Listado de Profesionales Ordenados por Apellido

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g7_sf#6]
**Descripción:** Crear un endpoint que recupere el listado de profesionales ordenados alfabéticamente por apellido. Además, eliminar constructores y anotaciones @Table y @Column innecesarias o redundantes.

**Tareas:**

1. Crear un método en el repositorio `ProfesionalRepository` para recuperar el listado de profesionales ordenados por apellido.
2. Implementar el endpoint correspondiente en el controlador.
3. Eliminar constructores innecesarios y anotaciones @Table y @Column redundantes en la entidad `Profesional`.
4. Probar los cambios y adjuntar una captura de Postman con la petición GET del listado ordenado.

**Ejemplo de Desarrollo en el Repository:**

```java

    package imb.gc4.turnero.repository;
    
    import java.util.List;
    import org.springframework.data.jpa.repository.JpaRepository;
    import imb.gc4.turnero.entity.Profesional;
    
    public interface ProfesionalRepository extends JpaRepository<Profesional, Integer> {
        List<Profesional> findAllByOrderByApellidoProfesionalAsc();
    }
```

**Comment by RoxanaArenas** [comment]
![Uploading postman get.png…]()
