### ISSUE TITLE
Filtrar Turnos por Fecha

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g7_sf#7]
**Descripción:** Crear un endpoint que permita filtrar turnos por fecha. Además, eliminar constructores y anotaciones @Table y @Column innecesarias o redundantes.

**Tareas:**

1. Crear un método en el repositorio `TurnoRepository` para filtrar turnos por fecha.
2. Implementar el endpoint correspondiente en el controlador.
3. Eliminar constructores innecesarios y anotaciones @Table y @Column redundantes en la entidad `Turno`.
4. Probar los cambios y adjuntar una captura de Postman con la petición GET del filtrado de turnos por fecha.

**Ejemplo de Desarrollo en el Repository:**

```java
    package imb.gc4.turnero.repository;
    
    import java.util.List;
    import java.time.LocalDateTime;
    import org.springframework.data.jpa.repository.JpaRepository;
    import imb.gc4.turnero.entity.Turno;
    
    public interface TurnoRepository extends JpaRepository<Turno, Integer> {
        List<Turno> findByFechaYHoraBetween(LocalDateTime startDate, LocalDateTime endDate);
    }

```

**Comment by Valen-D** [comment]
Profe no me deja hacer el push me da errores de permiso 
![error](https://github.com/ahumadamob/2024_gc_p3_g7_sf/assets/89789683/bd7df0b6-0ae3-4a93-911f-456da46cbf89)
Valen@DESKTOP-31HP7MG MINGW64 ~/Desktop/VALEN/C/programacion_3/turnero/2024_gc_p3_g7_sf (7-filtrar-turnos-por-fecha)
$ git push
remote: Permission to ahumadamob/2024_gc_p3_g7_sf.git denied to Valen-D.
fatal: unable to access 'https://github.com/ahumadamob/2024_gc_p3_g7_sf.git/': T
he requested URL returned error: 403

**Comment by ahumadamob** [comment]
Fijate por favor a continuación si el usuario de git que he agregado es el usuario que estás usando para hacer el push. Al parecer, son diferentes
![image](https://github.com/ahumadamob/2024_gc_p3_g7_sf/assets/12868283/6ee9a8ff-b80f-426d-9c57-05581db9e5a0)
