### ISSUE TITLE
Listado de Salas Ordenadas por Nombre

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g7_sf#8]
**Descripción:** Crear un endpoint que recupere el listado de salas ordenadas alfabéticamente por nombre. Además, eliminar constructores y anotaciones @Table y @Column innecesarias o redundantes.

**Tareas:**

1. Crear un método en el repositorio `SalaRepository` para recuperar el listado de salas ordenadas por nombre.
2. Implementar el endpoint correspondiente en el controlador.
3. Eliminar constructores innecesarios y anotaciones @Table y @Column redundantes en la entidad `Sala`.
4. Probar los cambios y adjuntar una captura de Postman con la petición GET del listado ordenado.

**Ejemplo de Desarrollo en el Repository:**

```java
    package imb.gc4.turnero.repository;
    
    import java.util.List;
    import org.springframework.data.jpa.repository.JpaRepository;
    import imb.gc4.turnero.entity.Sala;
    
    public interface SalaRepository extends JpaRepository<Sala, Integer> {
        List<Sala> findAllByOrderByNombreAsc();
    }

```

**Comment by RoxanaArenas** [comment]
![postman get](https://github.com/ahumadamob/2024_gc_p3_g7_sf/assets/83459444/4fb0f88c-6b18-4d03-8909-22bffa855e22)
